// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// beta_newton_cpp
List beta_newton_cpp(const arma::mat& Wmat, const arma::ivec& grp, const arma::ivec& true_idx, arma::vec beta, int maxit, double tol, int max_halving, double ridge);
RcppExport SEXP _SeMaCoPE_beta_newton_cpp(SEXP WmatSEXP, SEXP grpSEXP, SEXP true_idxSEXP, SEXP betaSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP max_halvingSEXP, SEXP ridgeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Wmat(WmatSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type grp(grpSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type true_idx(true_idxSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_halving(max_halvingSEXP);
    Rcpp::traits::input_parameter< double >::type ridge(ridgeSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_newton_cpp(Wmat, grp, true_idx, beta, maxit, tol, max_halving, ridge));
    return rcpp_result_gen;
END_RCPP
}
// covariate_setup_core_sat2_cpp
List covariate_setup_core_sat2_cpp(NumericVector x, NumericVector y, IntegerVector type, int p, double R_within, double R_between, double sat_within, double sat_between, bool want_components);
RcppExport SEXP _SeMaCoPE_covariate_setup_core_sat2_cpp(SEXP xSEXP, SEXP ySEXP, SEXP typeSEXP, SEXP pSEXP, SEXP R_withinSEXP, SEXP R_betweenSEXP, SEXP sat_withinSEXP, SEXP sat_betweenSEXP, SEXP want_componentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type R_within(R_withinSEXP);
    Rcpp::traits::input_parameter< double >::type R_between(R_betweenSEXP);
    Rcpp::traits::input_parameter< double >::type sat_within(sat_withinSEXP);
    Rcpp::traits::input_parameter< double >::type sat_between(sat_betweenSEXP);
    Rcpp::traits::input_parameter< bool >::type want_components(want_componentsSEXP);
    rcpp_result_gen = Rcpp::wrap(covariate_setup_core_sat2_cpp(x, y, type, p, R_within, R_between, sat_within, sat_between, want_components));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SeMaCoPE_beta_newton_cpp", (DL_FUNC) &_SeMaCoPE_beta_newton_cpp, 8},
    {"_SeMaCoPE_covariate_setup_core_sat2_cpp", (DL_FUNC) &_SeMaCoPE_covariate_setup_core_sat2_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_SeMaCoPE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
