# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

omp_max_threads_cpp <- function() {
    .Call(`_SeMaCoPE_omp_max_threads_cpp`)
}

beta_newton_omp_cpp <- function(Wmat, grp, true_idx, beta, nthreads = 1L, maxit = 100L, tol = 1e-8, max_halving = 30L, ridge = 1e-8, block = 64L) {
    .Call(`_SeMaCoPE_beta_newton_omp_cpp`, Wmat, grp, true_idx, beta, nthreads, maxit, tol, max_halving, ridge, block)
}

beta_newton_cpp <- function(Wmat, grp, true_idx, beta, maxit = 100L, tol = 1e-8, max_halving = 30L, ridge = 1e-8) {
    .Call(`_SeMaCoPE_beta_newton_cpp`, Wmat, grp, true_idx, beta, maxit, tol, max_halving, ridge)
}

covariate_setup_core_cpp <- function(x, y, type, p, R_within, R_between, sat_i, want_components = TRUE) {
    .Call(`_SeMaCoPE_covariate_setup_core_cpp`, x, y, type, p, R_within, R_between, sat_i, want_components)
}

covariate_setup_core_sat2_cpp <- function(x, y, type, p, R_within, R_between, sat_within, sat_between, want_components = TRUE) {
    .Call(`_SeMaCoPE_covariate_setup_core_sat2_cpp`, x, y, type, p, R_within, R_between, sat_within, sat_between, want_components)
}

