# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

beta_newton_cpp <- function(Wmat, grp, true_idx, beta, maxit = 100L, tol = 1e-8, max_halving = 30L, ridge = 1e-8) {
    .Call(`_SeMaCoPE_beta_newton_cpp`, Wmat, grp, true_idx, beta, maxit, tol, max_halving, ridge)
}

covariate_setup_core_sat2_cpp <- function(x, y, type, p, R_within, R_between, sat_within, sat_between, want_components = TRUE) {
    .Call(`_SeMaCoPE_covariate_setup_core_sat2_cpp`, x, y, type, p, R_within, R_between, sat_within, sat_between, want_components)
}

